In [14]:
from sklearn.model_selection import train_test_split
from Naive_Bayes import NaiveBayes
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score

In [15]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
df['Category'] = df['Category'].map({'ham': 0,'spam': 1})

In [17]:
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [18]:
df['Category'].value_counts()

Category
0    4825
1     747
Name: count, dtype: int64

In [19]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['Message']).toarray()
y = df['Category'].values

In [20]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
print(y)

[0 0 1 ... 0 0 0]


In [22]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [23]:
model = NaiveBayes()
model.fit(X_train,y_train)

In [24]:
y_pred = model.predict(X_test)

print('Predicted:',y_pred)
print('Actual:',y_test)

c:\Users\DELL\Desktop\ml\Naive-Bayes-Classifier\Naive_Bayes.py:43: RuntimeWarning: divide by zero encountered in divide
  numerator = np.exp(-((x - mean)**2) / (2 * var))
c:\Users\DELL\Desktop\ml\Naive-Bayes-Classifier\Naive_Bayes.py:43: RuntimeWarning: invalid value encountered in divide
  numerator = np.exp(-((x - mean)**2) / (2 * var))
c:\Users\DELL\Desktop\ml\Naive-Bayes-Classifier\Naive_Bayes.py:45: RuntimeWarning: invalid value encountered in divide
  return numerator / denominator
c:\Users\DELL\Desktop\ml\Naive-Bayes-Classifier\Naive_Bayes.py:34: RuntimeWarning: divide by zero encountered in log
  posterior = np.sum(np.log(self._pdf(idx,x)))


Predicted: [0 0 0 ... 0 0 0]
Actual: [0 0 0 ... 0 0 0]


In [25]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy*100)

86.63677130044843
